AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 300
    MemorySize: 128
Resources:
  ImageGenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cara011bucket/855e78ef8cec05e00997b1d8cc703a46
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          S3_BUCKET: pgr301-couch-explorers
          CANDIDATE_NR: '55'
      Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          Effect: Allow
          Action:
          - s3:PutObject
          Resource:
          - arn:aws:s3:::pgr301-couch-explorers/55/*
      - Statement:
          Effect: Allow
          Action:
          - bedrock:InvokeModel
          Resource: '*'
      Architectures:
      - x86_64
      Events:
        ImageGen:
          Type: Api
          Properties:
            Path: /generate
            Method: post
    Metadata:
      SamResourceId: ImageGenFunction
Outputs:
  ImageGenApi:
    Description: API Gateway endpoint URL for Prod stage for Image Gen function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate/
  ImageGenFunction:
    Description: Image Gen Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ImageGenFunction
      - Arn
  ImageGenIamRole:
    Description: Implicit IAM Role created for Image Gen Function
    Value:
      Fn::GetAtt:
      - ImageGenFunctionRole
      - Arn
