AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 350
    MemorySize: 128

Resources:
  ImageGenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./image_gen/app.py
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment: 
        Variables:
          S3_BUCKET: "pgr301-couch-explorers"
          CANDIDATE_NR: "55"
      Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          Effect: Allow
          Action:
            - "s3:PutObject"
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::pgr301-couch-explorers/55/*"
      - Statement:
          Effect: Allow
          Action:
            -  "bedrock:InvokeModel"
          Resource: "*"
      Architectures:
        - x86_64
      Events:
        ImageGen:
          Type: Api
          Properties:
            Path: /generate
            Method: post


#Edited from the original SAM-app template generator
Outputs:
  ImageGenApi:
    Description: "API Gateway endpoint URL for Prod stage for Image Gen function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate/"
  ImageGenFunction:
    Description: "Image Gen Lambda Function ARN"
    Value: !GetAtt ImageGenFunction.Arn
  ImageGenIamRole:
    Description: "Implicit IAM Role created for Image Gen Function"
    Value: !GetAtt ImageGenFunctionRole.Arn
