name: Deploy SQS Resources

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure:
    name: Deploy SQS and Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Debug Repository Structure
      run: |
        echo "Current Directory:"
        pwd
        echo "Repository Structure:"
        ls -R
  
    - name: Validate SAM Template for Infrastructure
      run: |
        sam validate -t sam-app/template.yaml

    - name: Build SAM Application for Infrastructure
      run: |
        sam build -t sam-app/template.yaml

    - name: Deploy SAM Stack for Infrastructure
      run: |
        sam deploy --stack-name sqs-stack --template-file .aws-sam/build/template.yaml --capabilities CAPABILITY_IAM --region eu-west-1
