name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Triggers workflow on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          rev=$(git rev-parse --short HEAD)
          docker build -f ./java_sqs_client/Dockerfile . -t cara011_java_sqs_client
          
          docker tag cara011_java_sqs_client ${{ secrets.DOCKER_USERNAME }}/cara_java_sqs_client:$rev
          docker push ${{ secrets.DOCKER_USERNAME }}/cara011_java_sqs_client:$rev
          
          docker tag cara011_java_sqs_client ${{ secrets.DOCKER_USERNAME }}/cara011_java_sqs_client:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cara011_java_sqs_client:latest