name: Workflows with large secrets

on:
  push:
    branches:
      - main

jobs:
  my-job:
  
    name: App Deploy on Push
    
    runs-on: ubuntu-latest #Amazon runs on linux right?!?!
    steps:
      - name: checkout commit
        uses: actions/checkout@v3

      - name: AWS CLi
        uses: aws-actions/configure-aws-credentials@v2 #v2? v4?
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: eu-west-1
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli
      - name: Validate SAM Template
        run: |
          sam validate -t sam-app/template.yaml
      - name: Re-pack SAM APP
        run: |
          sam package -t sam-app/template.yaml --output-template-file lambda-pkgd.yaml --s3-bucket cara011bucket
      - name: Deploy SAM application
        run: |
            sam deploy -t sam-app/template.yaml --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-sentiment-CAR  --capabilities CAPABILITY_IAM --region eu-west-1
